name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          RUSTFLAGS: "--cfg tracing_unstable"
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
        env:
          RUSTFLAGS: "--cfg tracing_unstable"